//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLocalizationResx.LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationInfoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationInfoRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfLocalizationResx.LocalResources.LocalizationInfoRes", typeof(LocalizationInfoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 E_xit 的本地化字符串。
        /// </summary>
        public static string btnExit_Content {
            get {
                return ResourceManager.GetString("btnExit.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right to left 的本地化字符串。
        /// </summary>
        public static string chkRightToLeft_Content {
            get {
                return ResourceManager.GetString("chkRightToLeft.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English (en-US) 的本地化字符串。
        /// </summary>
        public static string cmbLanguageItem1 {
            get {
                return ResourceManager.GetString("cmbLanguageItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German (de-DE) 的本地化字符串。
        /// </summary>
        public static string cmbLanguageItem2 {
            get {
                return ResourceManager.GetString("cmbLanguageItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hebrew (he-IL) 的本地化字符串。
        /// </summary>
        public static string cmbLanguageItem3 {
            get {
                return ResourceManager.GetString("cmbLanguageItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap CountryFlag {
            get {
                object obj = ResourceManager.GetObject("CountryFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Locale Information 的本地化字符串。
        /// </summary>
        public static string gbLocaleInformation_Header {
            get {
                return ResourceManager.GetString("gbLocaleInformation.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value Display Input 的本地化字符串。
        /// </summary>
        public static string gbValueInput_Header {
            get {
                return ResourceManager.GetString("gbValueInput.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bound Values 的本地化字符串。
        /// </summary>
        public static string grpBoundValues_Header {
            get {
                return ResourceManager.GetString("grpBoundValues.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attached Property (Content/Tooltip): 的本地化字符串。
        /// </summary>
        public static string lblAttachedLabel_Content {
            get {
                return ResourceManager.GetString("lblAttachedLabel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello World (Res) 的本地化字符串。
        /// </summary>
        public static string lblAttachedValue_Content {
            get {
                return ResourceManager.GetString("lblAttachedValue.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100 的本地化字符串。
        /// </summary>
        public static string lblAttachedValue_Margin {
            get {
                return ResourceManager.GetString("lblAttachedValue.Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello World Tooltip 的本地化字符串。
        /// </summary>
        public static string lblAttachedValue_Tooltip {
            get {
                return ResourceManager.GetString("lblAttachedValue.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a date value: 的本地化字符串。
        /// </summary>
        public static string lblDateLabel_Content {
            get {
                return ResourceManager.GetString("lblDateLabel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow Direction: 的本地化字符串。
        /// </summary>
        public static string lblFlowDirectionName_Content {
            get {
                return ResourceManager.GetString("lblFlowDirectionName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Language: 的本地化字符串。
        /// </summary>
        public static string lblLanguageSelections_Content {
            get {
                return ResourceManager.GetString("lblLanguageSelections.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date Time: 的本地化字符串。
        /// </summary>
        public static string lblLocalDateTimeName_Content {
            get {
                return ResourceManager.GetString("lblLocalDateTimeName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locale: 的本地化字符串。
        /// </summary>
        public static string lblLocale_Content {
            get {
                return ResourceManager.GetString("lblLocale.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisplayName: 的本地化字符串。
        /// </summary>
        public static string lblLocaleName_Content {
            get {
                return ResourceManager.GetString("lblLocaleName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeric: 的本地化字符串。
        /// </summary>
        public static string lblLocaleNumberName_Content {
            get {
                return ResourceManager.GetString("lblLocaleNumberName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Native Name: 的本地化字符串。
        /// </summary>
        public static string lblNativeName_Content {
            get {
                return ResourceManager.GetString("lblNativeName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a numeric value: 的本地化字符串。
        /// </summary>
        public static string lblNumberLabel_Content {
            get {
                return ResourceManager.GetString("lblNumberLabel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello World Markup Extension Default: 的本地化字符串。
        /// </summary>
        public static string lblResxHelloWorldMarkupExtension1Label_Content {
            get {
                return ResourceManager.GetString("lblResxHelloWorldMarkupExtension1Label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today Markup Extensions Explicit: 的本地化字符串。
        /// </summary>
        public static string lblResxHelloWorldMarkupExtension2Label_Content {
            get {
                return ResourceManager.GetString("lblResxHelloWorldMarkupExtension2Label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello World Strong Type: 的本地化字符串。
        /// </summary>
        public static string lblResxHelloWorldStrongLabel_Content {
            get {
                return ResourceManager.GetString("lblResxHelloWorldStrongLabel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Theme: 的本地化字符串。
        /// </summary>
        public static string lblThemeSelection_Content {
            get {
                return ResourceManager.GetString("lblThemeSelection.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_xit 的本地化字符串。
        /// </summary>
        public static string mnuExit_Header {
            get {
                return ResourceManager.GetString("mnuExit.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string mnuFile_Header {
            get {
                return ResourceManager.GetString("mnuFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string mnuHelp_Header {
            get {
                return ResourceManager.GetString("mnuHelp.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string mnuHelpAbout_Header {
            get {
                return ResourceManager.GetString("mnuHelpAbout.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help Content 的本地化字符串。
        /// </summary>
        public static string mnuHelpContent_Header {
            get {
                return ResourceManager.GetString("mnuHelpContent.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        public static string mnuSave_Header {
            get {
                return ResourceManager.GetString("mnuSave.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goodbye (Res) 的本地化字符串。
        /// </summary>
        public static string MyContext_GoodBye_Header {
            get {
                return ResourceManager.GetString("MyContext_GoodBye.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello Context (Res) 的本地化字符串。
        /// </summary>
        public static string MyContext_Hello_Header {
            get {
                return ResourceManager.GetString("MyContext_Hello.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Localization Info 的本地化字符串。
        /// </summary>
        public static string wndLocalizationInfo_Title {
            get {
                return ResourceManager.GetString("wndLocalizationInfo.Title", resourceCulture);
            }
        }
    }
}
